apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  claimRef:
    namespace: prometheus
    name: prometheus-server
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"