apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 4Gi
  claimRef:
    namespace: prometheus
    name: storage-prometheus-alertmanager-0
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/alertmanager"