apiVersion: v1
kind: Service
metadata:
  name: api-service-canary
  namespace: qa
spec:
  selector:
    app: api-service-canary
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000