apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.3.0
    helm:
      parameters:
      # - k8s/argocd-apps/ingress-nginx/vlerat.yaml
        - name: admissionWebhooks.failurePolicy
          value: 'Ignore'
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.metrics.service.annotations
          value: "{'prometheus.io/scrape: true', 'prometheus.io/port: 10254'}"
        # - name: controller.metrics.service.annotations
        #   value: "prometheus.io/port: 10254"
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true