apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.3.0
    helm:
      values:
# {{ .Files.Get "vlerat.yaml" | indent 8 }}
      - k8s/argocd-apps/ingress-nginx/values.yaml
      # parameters:
      #   - name: admissionWebhooks.failurePolicy
      #     value: 'Ignore'
      #   - name: controller.metrics.port
      #     value: 9090
      #   - name: controller.metrics.service.annotations.prometheus.io/scrape
      #     value: "true"
      #   - name: controller.metrics.service.annotations.prometheus.io/port
      #     value: "9090"
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true