apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8s
  namespace: akv2k8s
spec:
  project: default
  source:
    repoURL: 'http://charts.spvapi.no'
    targetRevision: 2.2.2
    helm:
      parameters:
        - name: admissionWebhooks.failurePolicy
          value: 'Ignore'
    chart: spv-charts/akv2k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: akv2k8s
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true