apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8s
  namespace: akv2k8s
spec:
  project: default
  source:
    repoURL: 'https://github.com/ErgiKame/Argo-PoC'
    path: k8s/akv2k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: akv2k8s
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true