apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - api-qa.yaml
  - argocd-image-updater.yaml
  - kubeseal.yaml
  - akv2k8s.yaml
  - namespaces.yaml
  