apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - ingress-nginx/ingress-nginx.yaml
  - api.yaml
  # - argocd-image-updater.yaml
  - kubeseal.yaml
  - argo-rollouts.yaml
  - prometheus.yaml
  - grafana.yaml