apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 30s
    count: 2
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local:80
        query: sum(kube_pod_status_ready{condition="false"})
        
        # sum(response_status{app="{{args.service-name}}",role="canary",status=~"2.*"})/sum(response_status{app="{{args.service-name}}",role="canary"})
        
        # sum (rate (container_cpu_usage_seconds_total{image!="docker.io/ergikame/hyra-frontend:0.0.994"}[1m])) by (pod_name)