apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: qa
  labels:
    app.kubernetes.io/instance: api
spec:
  dnsNames:
    - api.argotest.tk
  secretName: api-new-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer