apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
- ../../base
- sealed-secret.yaml
- ingress.yaml
- cert.yaml
- namespace.yaml

patchesStrategicMerge:
- rollout.yaml