apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        linkerd.io/inject: enabled 
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ergikame/hyra-frontend:0.0.994
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: DOCKER_IMAGE_VERSION
            value: "1234"
  strategy:
    canary:
      canaryService: api-service-canary  # required
      stableService: api-service  # required
      trafficRouting:
        nginx:
          stableIngress: api-ingress  # required
      steps:
      - setWeight: 20
      - pause: {duration: 3m}
      - analysis:
          templates:
          - templateName: success-rate
          # - templateName: random-fail
            clusterScope: false
          args:
          - name: service-name
            value: api
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
