apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecrets
  namespace: default
spec:
  encryptedData:
    ENV: AgChltJ+QdJDhQWs59k+eVBphyrADKy9my2Ou/nJN42YbKeoPb9DgUChGDoFCvhyGooi0R878ENQuNEMxxe5THP8S292p+9DL0HORbJ7QLjZm5IbwDPKlkmJFV8K7CDyx3HPuN5UXWS3z3tQL5Zo9UPT2Dj9B2r00LfpR1iXqqwgvYh6itSJ+SusIDS9FqVNjgsVzX+DV92/30/dhojhwYHEghZkYjV67XtbT+O4gmyB9Bez2si37GVeYYFVg/GR/SrddeQfa73UOXpY5bCSwyj5HP2ff9gvG8cEC05p67EnHkG4HW0mS4QOGUXOQqzPak8zuqCzFxIwVCmaBYo3HXwRd3R4D398GklTl6K5H/CGP853HAAWPPti7bKUYhbW6NvFpBFLcc/2AcnMh8bFRQdlSo6qoy7ytsI5z9aHaF70CQfZolcYazVV3FJurLDTMJxC6qBSvcu1JM6lhMxvMNQGk3jnjF2fLB/mSEW9HbD/oEA74YY71gnCdKKfBZ2QqEmrEj7n6Awt/Xlisp20jFsjplcNRyifPHxkw2NqZqcQdR6QUE5Uu+XiJ54CXFecOE3yqbuXSn2jBSit1EOk0dEeSPpj/786ESzN8arGOpgEC92R/aBmDWwJwRtwBPc2gyUP4KOdonwyAkpa+dETOUhqx2GmcvWOTQZ5/E0w6sgVQFmR6A0RyuxoZxcdIcsATfFC63sj
  template:
    metadata:
      creationTimestamp: null
      name: mysecrets
      namespace: default
    type: Opaque

