apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecrets
  namespace: default
spec:
  encryptedData:
    ENV: AgBxFOHLXMnslcBBbzlyNX23q9RrF2PhKZlmbYb+5unQNpbSJCu1Dcg9zUZ58wksr8TmFZ+aCQ1ev+ic2NxJXs6DXn9+J7SnjKMzwFH4LUsT4uqSQ0IjbLEu/HrGPF0ZxbZCnP7e5yfGvMhuVCwn4rhnWhAUiBln7d/MsXF0Oye8VGC5+a0z46+hlav0DciXQ6cICJp6YWwmb7PBQN0lfC4Z7p2tgRtofW7vh2XVsU3TvI1DiqPCuw6b82MHfCqhuIibcLdANu4LFWcbgiKJR5xNy2DSjR0WE1k31mQiqwV2KpwvKwgwWXgjmALLkfDPbVOq6fe2fRqt6TLXUIyCmFDEpTZoqNP81YKpAbuQSDTkvd7RtAz5CLLkX6Uv3nc9irYBWovLKiseo8Ni+isRNsfVVEw6pPJEA0VqavfZuMfSMVg6ehl+tr1Y2KLbhXAAUEe+M8HaSQ88BITGtKh+Sqey1MbzQ2Zg10uWO+c/4ilZTMbw69CeQWI91vCjSV11j7Zi/cL5oRsuwDES9GRTSPfa9fDrNGiC8T+AOYTE7kwJrK/39bmYRAvugblUw3HDz2hOZfF9WVZcIm1yufSYh6Lmhvl5jsELphfUcC98XQ2OLoKOwo1hV60itZQwLIkfVldJHsg9wZGXrsLF2FViZkDkdcwgDRt5GAAX+Z45n5PCCj4Nv/xa38mcvbBMVry9LgMQaSTD
  template:
    metadata:
      creationTimestamp: null
      name: mysecrets
      namespace: default
    type: Opaque

