apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argotest.tk

  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-sso:client-id
          clientSecret: $github-sso:client-secret