apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  - cert.yaml
  - ingress.yaml

patchesStrategicMerge:
  - argo-cm.yaml
